# Generated by Django 4.2.23 on 2025-06-22 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('message_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('called', 'Вызван'), ('coming', 'В пути'), ('arrived', 'Подошел'), ('cancelled', 'Отменен')], default='called', max_length=20)),
                ('called_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
