# Generated by Django 4.2.23 on 2025-06-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitercall',
            name='coming_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waitercall',
            name='status',
            field=models.CharField(choices=[('called', 'Вызван'), ('coming', 'В пути'), ('arrived', 'Подошел')], default='called', max_length=20),
        ),
    ]
