"""
Django settings for franklin_api project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2o@y!&#5u)qyw_%t6=kn2hx=x6n#$kd3q!z786!)-@pfmh710t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'menu',
    'telegrambot',
    'drf_yasg',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'franklin_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'franklin_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # Это нужно для UI
    ]
}


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


CORS_ALLOW_ALL_ORIGINS = True


# TELEGRAM_BOT_TOKENS = {
#     'hookah': os.getenv('HOOKAH_BOT_TOKEN', '8039708999:AAGfnGGnoZLL2_wzWk_9hVJeSxWqg8886gA'),
#     'cook': os.getenv('COOK_BOT_TOKEN', '7937803037:AAEk2kGyIDDm1u0a4KVOLtET0moUKWDXRMM'),
#     'waiter': os.getenv('WAITER_BOT_TOKEN', '7412228739:AAGsDU2DSXpaz8db17uqm7Za5kT-f3M-kSo'),
#     'universal': os.getenv('UNIVERSAL_BOT_TOKEN', '7947420504:AAHf8xrHF_y61qa5CUqxZc15DiMlrSxs-Ik'),
# }


TELEGRAM_BOT_TOKENS = {
    'hookah': '8039708999:AAGfnGGnoZLL2_wzWk_9hVJeSxWqg8886gA',
    'cook': '7937803037:AAEk2kGyIDDm1u0a4KVOLtET0moUKWDXRMM',
    'waiter': '7412228739:AAGsDU2DSXpaz8db17uqm7Za5kT-f3M-kSo',
    'universal': '7947420504:AAHf8xrHF_y61qa5CUqxZc15DiMlrSxs-Ik',
}



ALLOWED_TELEGRAM_USERNAMES = ['usm0n0v1ch']


TELEGRAM_USER_ROLES = {
    'usm0n0v1ch': 'waiter',
    'anaptyx': 'cook',
    'anaptyxuz': 'hookah',
}

TELEGRAM_UNIVERSAL_TOKEN ='7947420504:AAHf8xrHF_y61qa5CUqxZc15DiMlrSxs-Ik'