# Generated by Django 4.2.23 on 2025-06-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
