# Generated by Django 4.2.23 on 2025-06-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
