# Generated by Django 4.2.23 on 2025-06-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_orderitem_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
